CTI_L4T_VERSION ?= "35.6.0"
CTI_BSP_RELEASE_VERSION ?= "V005"
CTI_BSP_VERSION ?= "${CTI_L4T_VERSION}-${CTI_BSP_RELEASE_VERSION}"
CTI_BSP_SHARED_BASE_DIR = "${TMPDIR}/work-shared/${CTI_SOM_BSP}-${CTI_BSP_VERSION}"
